// ============================================================
//  season/teams.js — Team roster for this event
//  !! UPDATE THIS FILE EACH EVENT !!
// ============================================================
//
//  Johnson Division — 2026 FRC World Championship
//  George R. Brown Convention Center, Houston TX
//  April 29 – May 2, 2026
//
//  Generated from TBA: /event/2026joh/teams
//
// ============================================================

var TEAM_DATA = {
  "8":     { name: "Paly Robotics",                city: "Palo Alto",           state: "CA", img: "" },
  "33":    { name: "Killer Bees",                  city: "Bloomfield Hills",    state: "MI", img: "" },
  "48":    { name: "Team E.L.I.T.E.",              city: "Warren",              state: "OH", img: "" },
  "67":    { name: "The HOT Team",                 city: "Highland",            state: "MI", img: "" },
  "117":   { name: "Steel Dragons",                city: "Pittsburgh",          state: "PA", img: "" },
  "118":   { name: "Robonauts",                    city: "Houston",             state: "TX", img: "" },
  "179":   { name: "Children of the Swamp",        city: "Riviera Beach",       state: "FL", img: "" },
  "190":   { name: "Gompei and the HERD",          city: "Worcester",           state: "MA", img: "" },
  "245":   { name: "Adambots",                     city: "Rochester Hills",     state: "MI", img: "" },
  "321":   { name: "RoboLancers",                  city: "Philadelphia",        state: "PA", img: "" },
  "334":   { name: "TechKnights",                  city: "Brooklyn",            state: "NY", img: "" },
  "360":   { name: "The Revolution",               city: "Tacoma",              state: "WA", img: "" },
  "422":   { name: "The Mech Tech Dragons",        city: "Richmond",            state: "VA", img: "" },
  "498":   { name: "The Cobra Commanders",         city: "Glendale",            state: "AZ", img: "" },
  "619":   { name: "Cavalier Robotics",            city: "Charlottesville",     state: "VA", img: "" },
  "772":   { name: "Sabre Bytes Robotics",         city: "LaSalle",             state: "ON", img: "" },
  "836":   { name: "The RoboBees",                 city: "Hollywood",           state: "MD", img: "" },
  "955":   { name: "Ctrl C",                       city: "Corvallis",           state: "OR", img: "" },
  "1002":  { name: "CircuitRunners Robotics",      city: "Marietta",            state: "GA", img: "" },
  "1073":  { name: "The Force Team",               city: "Hollis",              state: "NH", img: "" },
  "1076":  { name: "PiHi Samurai",                 city: "Ann Arbor",           state: "MI", img: "" },
  "1306":  { name: "BadgerBOTS",                   city: "Middleton",           state: "WI", img: "" },
  "1792":  { name: "Round Table Robotics",         city: "Oak Creek",           state: "WI", img: "" },
  "1908":  { name: "ShoreBots",                    city: "Eastville",           state: "VA", img: "" },
  "2040":  { name: "DERT",                         city: "Dunlap",              state: "IL", img: "" },
  "2096":  { name: "RoboActive",                   city: "Dimona",              state: "ISR", img: "" },
  "2252":  { name: "The Mavericks",                city: "Milan",               state: "OH", img: "" },
  "2337":  { name: "EngiNERDs",                    city: "Grand Blanc",         state: "MI", img: "" },
  "2522":  { name: "Royal Robotics",               city: "Bothell",             state: "WA", img: "" },
  "2619":  { name: "The Charge",                   city: "Midland",             state: "MI", img: "" },
  "2638":  { name: "Rebel Robotics",               city: "Great Neck",          state: "NY", img: "" },
  "2704":  { name: "Roaring Robotics",             city: "Naperville",          state: "IL", img: "" },
  "2848":  { name: "Rangers",                      city: "Dallas",              state: "TX", img: "" },
  "2877":  { name: "LigerBots",                    city: "Newtonville",         state: "MA", img: "" },
  "3061":  { name: "Huskie Robotics",              city: "Naperville",          state: "IL", img: "" },
  "3255":  { name: "SuperNURDs",                   city: "Escondido",           state: "CA", img: "" },
  "3414":  { name: "Hackbots",                     city: "Farmington",          state: "MI", img: "" },
  "3536":  { name: "Electro Eagles",               city: "Hartland",            state: "MI", img: "" },
  "3603":  { name: "Cyber Coyotes",                city: "Reed City",           state: "MI", img: "" },
  "3620":  { name: "Average Joes",                 city: "Saint Joseph",        state: "MI", img: "" },
  "3630":  { name: "Stampede",                     city: "Minneapolis",         state: "MN", img: "" },
  "3770":  { name: "BlitzCreek",                   city: "Midland",             state: "MI", img: "" },
  "4391":  { name: "BraveBots",                    city: "Gladstone",           state: "MI", img: "" },
  "4451":  { name: "ROBOTZ Garage",                city: "Laurens",             state: "SC", img: "" },
  "4522":  { name: "Team SCREAM",                  city: "Sedalia",             state: "MO", img: "" },
  "4635":  { name: "PrepaTec - Botbusters",        city: "Monterrey",           state: "MX", img: "" },
  "4946":  { name: "The Alpha Dogs",               city: "Bolton",              state: "ON", img: "" },
  "4967":  { name: "That ONE Team",                city: "Belmont",             state: "MI", img: "" },
  "5026":  { name: "Iron Panthers",                city: "Burlingame",          state: "CA", img: "" },
  "5968":  { name: "Little Apple Cyborgs",         city: "Manhattan",           state: "KS", img: "" },
  "6324":  { name: "The Blue Devils",              city: "Salem",               state: "NH", img: "" },
  "6652":  { name: "Tigres",                       city: "San Nicolas",         state: "MX", img: "" },
  "6766":  { name: "AtomStorm",                    city: "Shenzhen",            state: "CHN", img: "" },
  "6829":  { name: "Ignite Robotics",              city: "Suwanee",             state: "GA", img: "" },
  "6940":  { name: "Violet Z",                     city: "Shanghai",            state: "CHN", img: "" },
  "7220":  { name: "Steel Falcons",                city: "Brighton",            state: "MI", img: "" },
  "7257":  { name: "Semiconductors",               city: "Sauk Centre",         state: "MN", img: "" },
  "7403":  { name: "Lightning Blue Lizards",       city: "Envigado",            state: "COL", img: "" },
  "7551":  { name: "Extreme Mechanism",            city: "Zhuqi",               state: "TWN", img: "" },
  "7558":  { name: "ALT-F4",                       city: "North York",          state: "ON", img: "" },
  "7563":  { name: "SESI SENAI MEGAZORD",          city: "Jundiaí",             state: "BRA", img: "" },
  "8612":  { name: "Calvin Christian Robotics",    city: "Grandville",          state: "MI", img: "" },
  "9072":  { name: "TigerBots",                    city: "Hanover",             state: "MD", img: "" },
  "9277":  { name: "Sparkans",                     city: "Calgary",             state: "AB", img: "" },
  "9483":  { name: "Overcharge",                   city: "Cekmekoy",            state: "TUR", img: "" },
  "9484":  { name: "Robot's District",             city: "Taguatinga",          state: "BRA", img: "" },
  "9597":  { name: "Luban Robotics",               city: "Beijing",             state: "CHN", img: "" },
  "9646":  { name: "The Marinators",               city: "Southampton",         state: "NY", img: "" },
  "9757":  { name: "Mecha Marauders",              city: "Marlette",            state: "MI", img: "" },
  "10014": { name: "REBELLION",                    city: "Prosper",             state: "TX", img: "" },
  "10114": { name: "Phantom Talons",               city: "Zhonghe Dist",        state: "TWN", img: "" },
  "10217": { name: "Catahoula Blue Dogs",          city: "Port Allen",          state: "LA", img: "" },
  "10340": { name: "ITKAN Girls",                  city: "Plano",               state: "TX", img: "" },
  "10396": { name: "Mostra",                       city: "Istanbul",            state: "TUR", img: "" },
  "11269": { name: "Batteries Not Included",       city: "South Burlington",    state: "VT", img: "" },
};
